config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    root to: "skynets#new"
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  
  resources :skynets
  resources :vendors
  resources :vendor_categories
  resources :vendoritems
  resources :subscriptions
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  resources :users, only: [:edit, :update, :create, :new, :destroy]

  authenticated :user do
    root to: "skynets#new"
  end

  get '/plans' => 'subscriptions#plans'
  post '/stripe_checkout' => 'subscriptions#stripe_checkout'
  post '/subscription_checkout' => 'subscriptions#subscription_checkout'
  
  resources :companies

  get '/' => 'home#index'
  # defaults to dashboard
  root :to => redirect('/')

  # view routes
  get '/userlist' => 'home#userlist'
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index' 
  get 'dashboard/dashboard_buyer'
  get 'dashboard/dashboard_manager'
  get 'dashboard/dashboard_admin'
  get 'dashboard/dashboard_h'

  get 'skynets/download'
  get '/skynets/history' => 'skynets#history'

  post 'importskynet' => 'skynets#importskynet'
  post 'insertskynet' => 'skynets#insertskynet'

  namespace :api do
    get 'skynethisotry' => 'skynet#skynethisotry'
    
    get 'getitemlist' => 'vendoritem#getitemlist'
    post 'updatevendoritem' =>'vendoritem#updatevendoritem'
  end

  
  # get 'elements/button'
  # get 'elements/notification'
  # get 'elements/spinner'
  # get 'elements/animation'
  # get 'elements/dropdown'
  # get 'elements/nestable'
  # get 'elements/sortable'
  # get 'elements/panel'
  # get 'elements/portlet'
  # get 'elements/grid'
  # get 'elements/gridmasonry'
  # get 'elements/typography'
  # get 'elements/fonticons'
  # get 'elements/weathericons'
  # get 'elements/colors'
  # get 'elements/buttons'
  # get 'elements/notifications'
  # get 'elements/carousel'
  # get 'elements/tour'
  # get 'elements/sweetalert'
  # get 'forms/standard'
  # get 'forms/extended'
  get 'forms/validation'
  # get 'forms/wizard'
  # get 'forms/upload'
  # get 'forms/xeditable'
  # get 'forms/imgcrop'
  # get 'multilevel/level1'
  # get 'multilevel/level3'
  # get 'charts/flot'
  # get 'charts/radial'
  # get 'charts/chartjs'
  # get 'charts/chartist'
  # get 'charts/morris'
  # get 'charts/rickshaw'
  # get 'tables/standard'
  # get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  # get 'maps/google'
  # get 'maps/vector'
  # get 'extras/mailbox'
  # get 'extras/timeline'
  # get 'extras/calendar'
  # get 'extras/invoice'
  # get 'extras/search'
  # get 'extras/todo'
  # get 'extras/profile'
  # get 'extras/contacts'
  # get 'extras/contact_details'
  # get 'extras/projects'
  # get 'extras/project_details'
  # get 'extras/team_viewer'
  # get 'extras/social_board'
  # get 'extras/vote_links'
  # get 'extras/bug_tracker'
  # get 'extras/faq'
  # get 'extras/help_center'
  # get 'extras/followers'
  # get 'extras/settings'
  # get 'extras/plans'
  # get 'extras/file_manager'
  # get 'blog/blog'
  # get 'blog/blog_post'
  # get 'blog/blog_articles'
  # get 'blog/blog_article_view'
  # get 'ecommerce/ecommerce_orders'
  # get 'ecommerce/ecommerce_order_view'
  # get 'ecommerce/ecommerce_products'
  # get 'ecommerce/ecommerce_product_view'
  # get 'ecommerce/ecommerce_checkout'
  # get 'forum/forum_categories'
  # get 'forum/forum_topics'
  # get 'forum/forum_discussion'
  # get 'pages/login'
  # get 'pages/register'
  # get 'pages/recover'
  # get 'pages/lock'
  # get 'pages/template'
  # get 'pages/notfound'
  # get 'pages/maintenance'
  # get 'pages/error500'

  # # api routes
  # get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  # get '/api/skynethisotry' => 'api#skynethisotry'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  
  # get '/api/i18n/:locale' => 'api#i18n'
  # post '/api/xeditable' => 'api#xeditable'
  # get '/api/xeditable-groups' => 'api#xeditablegroups'

  # # the rest goes to root
  # get '*path' => redirect('/')

end

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2017 - FBM.Support</span>

app/views/layouts/partials/_homefooter.html.erb
<div class="clear"></div>
<div class="address">
<div class="container">
  <p class="copyright">2017-All Rights with FBA.Support </p>
</div>

app/views/layouts/partials/_hometopbar.erb
<div>
<header id="myPage">
  <nav>
    <div class="container">
      <div class="col-sm-4">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menus"> <span class="sr-only">Toggle navigation</span><i class="fa fa-bars" aria-hidden="true"></i> </button>
        <a class="logo" href="#"> <img src="<%= asset_path 'back/logo.png' %>"  class="img-responsive" alt=""> </a> </div>
      <div class="col-sm-8">
        <div class="collapse navbar-collapse" id="menus">
          <ul class="nav navbar-nav">
            <li> <a href="#top">Home</a> </li>
            <li> <a href="#features">Features</a> </li>
            <li> <a href="#services">Services</a> </li>
            <li> <a href="#contact">Contact</a> </li>
          
            <% if !current_user.present? %>
              <li class="font_Playfair"><%= link_to('SIGN UP', new_user_registration_path)  %> </li>
              <li class="font_Playfair"><%= link_to('SIGN IN', new_user_session_path)  %> </li>
            <% else %>
              <li class="font_Playfair"><%= link_to('SUBSCRIPTION', plans_path) %></li>
              <li class="font_Playfair"><%= link_to('SIGN OUT', destroy_user_session_path, :method => :delete) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="home_video">
    <video  autoplay loop>
      <source src="<%= asset_path 'FBA.mp4' %>" type="video/mp4" >
      <source src="<%= asset_path 'FBA.ogv' %>" type="video/ogv" >
    </video>
     <div class="banner_caption">
        <h1>Starting to sell on amazon? Not sure what to to sell?</h1>
        <h1>Our Amazon FBA tools help you identify and sell the right products! </h1>
        <div>
          <%= link_to(' Click here to start your free trial!', new_user_registration_path)  %>
        </div>
      </div> 
  </div>
</header>
</div>
<div>
</div>

app/views/layouts/partials/_hometopnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <div class ="brand-logo">
          <img src="<%= image_url('angle/logo.png') %>" alt="FBM Support" class="img-responsive">
        </div>
        <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/logo-single.png') %>" alt="FBA Support" class="img-responsive" />
         </div>
      <% end %>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div id="navbar2" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li class="font_Playfair active"><a href="#">HOME</a></li>
        <li class="font_Playfair"><a href="#">BLOG</a></li>
        <li class="font_Playfair"><a href="#">CAREER</a></li> -->
        <% if !current_user.present? %>
          <li class="font_Playfair"><%= link_to('SIGN UP', new_user_registration_path)  %> </li>
          <li class="font_Playfair"><%= link_to('SIGN IN', new_user_session_path)  %> </li>
        <% else %>
          <li class="font_Playfair"><%= link_to('SIGN OUT', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    </div>
</nav>
<!-- END Top Navbar-->

app/views/layouts/partials/_righttop.html.erb
<ul class="nav navbar-nav navbar-right">
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- Fullscreen (only desktops)-->
         <li class="visible-lg">
            <a href="#" data-toggle-fullscreen="">
               <em class="fa fa-expand"></em>
            </a>
         </li>
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">11</div>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
               <li>
                  
                  <!-- END list group-->
               </li>
            </ul>
            <!-- END Dropdown menu-->
         </li>
         <!-- END Alert menu-->
         <!-- START Contacts button-->
        <!--  <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li> -->
         <!-- END Contacts menu-->
      </ul>

app/views/layouts/partials/_sidebar.html.erb
<!-- START Sidebar (left)-->
<div class="aside-inner">
   <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="nav">
         <!-- START user info-->
         <li class="has-user-block">
            <div id="user-block" class="collapse">
               <div class="item user-block">
                  <!-- User picture-->
                  <!-- <div class="user-block-picture">
                     <div class="user-block-status">
                        <img src="<%= image_path('angle/user/02.jpg') %>" alt="Avatar" width="60" height="60" class="img-thumbnail img-circle" />
                        <div class="circle circle-success circle-lg"></div>
                     </div>
                  </div> -->
                  <!-- Name and Job-->
                  <div class="user-block-info">
                     <span class="user-block-name"><%= current_user.email %></span>
                     <span class="user-block-role"><%= current_user.role.name %> </span>
                  </div>
               </div>
            </div>
         </li>
         <!-- END user info-->
         <!-- Iterates over all sidebar items-->
         <li class="nav-heading">
            <span>Main Navigation</span>
         </li>
         <!-- <li class="<%= 'active' if controller?('dashboard')%>">
            <% if controller?('dashboard') && action_name == 'dashboard_buyer' %> 
               <%= link_to dashboard_dashboard_buyer_path do %>
                  <em class="icon-speedometer"></em>
                  <span class="hidden-sm hidden-xs">Dashboard</span>
               <% end %>
            <% elsif controller?('dashboard') && action_name == 'dashboard_manager' %>
               <%= link_to dashboard_dashboard_manager_path do %>
                  <em class="icon-speedometer"></em>
                  <span class="hidden-sm hidden-xs">Dashboard</span>
               <% end %>
            <% else %>
               <%= link_to dashboard_dashboard_admin_path do %>
                  <em class="icon-speedometer"></em>
                  <span class="hidden-sm hidden-xs">Dashboard</span>
               <% end %>
            <% end %>
               
         </li> -->

         <li class="<%= 'active ' if controller?('vendors')%>"><%= link_to('Catalogs', vendors_path(:user => current_user))  %> </li>
         <!-- <li class="<%= 'active' if controller?('vendors')%>">
            <a href="#vendor" title="Layouts" data-toggle="collapse">
               <em class="fa fa-briefcase"></em>
               <span>Vendors</span>
            </a>
            <ul id="vendor" class="nav sidebar-subnav collapse">
               <li class="<%= 'active' if controller?('vendors') && action?('index') %>">
                  <%= link_to 'List', vendors_path(:user => current_user) %>
               </li>
               <li class="<%= 'active' if controller?('vendor_categoreis') && action?('index') %>">
                  <%= link_to 'Category', vendor_categories_path %>
               </li>
            </ul>
         </li> -->

         <li class="<%= 'active' if controller?('vendoritems') || controller?('skynets')%>">
          <%= link_to 'Ready For Purchase', new_skynet_path(:company => current_user.company_id) %>
            <!-- <a href="#vendoritems" title="Layouts" data-toggle="collapse">
               <em class="fa fa-tags"></em>
               <span>Ready For Purchase</span>
            </a>
            <ul id="vendoritems" class="nav sidebar-subnav collapse">
                <li class="<%= 'active' if controller?('vendoritems') && action?('index') %>">
                  <%= link_to 'List', vendoritems_path(:company => current_user.company_id) %>
                </li>
                <li class="<%= 'active' if controller?('skynets') %>">
                  <a href="#skynet_page" title="Skynet" data-toggle="collapse">
                     <span>Skynet</span>
                  </a>
                  <ul id="skynet_page" class="nav sidebar-subnav collapse">
                      <li class="<%= 'active' if controller?('skynets') && action?('new') %>">
                        <%= link_to 'Upload', new_skynet_path() %>
                      </li>
                      <li class="<%= 'active' if controller?('skynets') && action?('index') %>">
                        <%= link_to 'List', skynets_path() %>
                      </li>
                  </ul>
               </li>
                
            </ul> -->
         </li>

         

         <% if current_user.role != 'Admin' %>
            <!-- <li class="<%= 'active' if controller?('skynets')%>">
               <a href="#skynet" title="Layouts" data-toggle="collapse">
                  <em class="fa fa-database"></em>
                  <span>Skynet</span>
               </a>
               <ul id="skynet" class="nav sidebar-subnav collapse">
                  <li class="<%= 'active' if controller?('skynets') && action?('new') %>">
                    <%= link_to 'New', new_skynet_path %>
                  </li>
                  <!--li class="<%= 'active' if controller?('skynets') && action?('list') %>">
                    <%= link_to 'List', skynets_path %>
                  </li
               </ul>
            </li> -->
         <% end %>
         
        <li class="<%= 'active' if controller?('companies') || controller?('registrations') %>">
            <a href="#setting" title="Setting" data-toggle="collapse">
               <em class="fa fa-briefcase"></em>
               <span>Setting</span>
            </a>
            <ul class="nave  sidebar-subnav collapse" id="setting">
              <% if current_user.role.name == 'Manager' %>
                <li class="<%= 'active' if controller?('companies')%>">
                  <a href="#company" title="Layouts" data-toggle="collapse">
                     <em class="icon-people"></em>
                     <span>Company Setting</span>
                  </a>
                  <ul id="company" class="nav sidebar-subnav collapse">
                    <li class="<%= 'active' if controller?('companies') && action?('edit') %>" >
                      <%= link_to edit_company_path(current_user.company) do %>
                         <span>Company</span>
                      <% end %>
                    </li>
                    <li class="<%= 'active' if controller?('companies') && action?('show') %>" >
                     <%= link_to company_path(current_user.role) do %>
                       <span>Users</span>
                     <% end %>
                    </li>
                  </ul>
                </li>
              <% elsif current_user.role.name == 'Admin' %>
                <li class="link">
                    <%= link_to companies_path do %>
                      <em class="icon-people"></em>
                      <span>Companies</span>
                    <% end %>
                </li>
              <% end %>
              <li class="<%= 'active' if controller?('users/registrations') %>">
                <%= link_to edit_user_registration_path do %>
                  <em class="icon-user"></em>
                  <span>Account</span>
                <% end %>
              </li>
            </ul>
        </li>

        
      </ul>
      <!-- END sidebar nav-->
   </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="<%= image_path('angle/logo.png') %>" alt="FBA Support" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/logo-single.png') %>" alt="FBA Support" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
         <!-- START User avatar toggle-->
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a id="user-block-toggle" href="#user-block" data-toggle="collapse">
               <em class="icon-user"></em>
            </a>
         </li>
         <!-- END User avatar toggle-->
         <!-- START lock screen-->
         <% if !current_user.present? %>
            <li><%= link_to('Login', new_user_session_path)  %> </li>
          <% else %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% end %>
         <!-- END lock screen-->
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

app/views/layouts/partials/_topnavbar_h.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="<%= image_path('angle/logo.png') %>" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/logo-single.png') %>" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="navbar-collapse collapse">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li></li>
         <li><a href="#dashboard" data-toggle="dropdown">Dashboard</a>
            <ul class="dropdown-menu animated fadeIn">
               <li class="<%= 'active' if controller?('dashboard') && action?('dashboard_v1') %>">
                  <a href="/dashboard/dashboard_v1">Dashboard v1</a>
               </li>
               <li class="<%= 'active' if controller?('dashboard') && action?('dashboard_v2') %>">
                  <a href="/dashboard/dashboard_v2">Dashboard v2</a>
               </li>
               <li class="<%= 'active' if controller?('dashboard') && action?('dashboard_v3') %>">
                  <a href="/dashboard/dashboard_v3">Dashboard v3</a>
               </li>
            </ul>
         </li>
         <li class="<%= 'active' if controller?('widgets') && action?('index') %>">
            <a href="/widgets">Widgets</a>
         </li>
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- START lock screen-->
         <li>
            <a href="/pages/lock" title="Lock screen">
               <em class="icon-lock"></em>
            </a>
         </li>
         <!-- END lock screen-->
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- Fullscreen (only desktops)-->
         <li class="visible-lg">
            <a href="#" data-toggle-fullscreen="">
               <em class="fa fa-expand"></em>
            </a>
         </li>
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">11</div>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
               <li>
                  <!-- START list group-->
                  <div class="list-group">
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-twitter fa-2x text-info"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New followers</p>
                              <p class="m0 text-muted">
                                 <small>1 new follower</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-envelope fa-2x text-warning"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New e-mails</p>
                              <p class="m0 text-muted">
                                 <small>You have 10 new emails</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-tasks fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">Pending Tasks</p>
                              <p class="m0 text-muted">
                                 <small>11 pending task</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- last list item -->
                     <a href="#" class="list-group-item">
                        <small>More notifications</small>
                        <span class="label label-danger pull-right">14</span>
                     </a>
                  </div>
                  <!-- END list group-->
               </li>
            </ul>
            <!-- END Dropdown menu-->
         </li>
         <!-- END Alert menu-->
         <!-- START Contacts button-->
         <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li>
         <!-- END Contacts menu-->
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

app/views/layouts/partials/_usertopbar.html.erb
  <nav>
    <div class="container">
      <div class="col-sm-4">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menus"> <span class="sr-only">Toggle navigation</span><i class="fa fa-bars" aria-hidden="true"></i> </button>
        <a class="logo" href="#"> <img src="<%= asset_path 'back/logo.png' %>"  class="img-responsive" alt=""> </a> </div>
      <div class="col-sm-8">
        <div class="collapse navbar-collapse" id="menus">
          <ul class="nav navbar-nav">
            <!-- <li> <a href="#top">Home</a> </li> -->
            <!-- <li> <a href="#part-two">Features</a> </li>
            <li> <a href="#part-three">Services</a> </li>
            <li> <a href="#part-four">Contact</a> </li> -->
            <li><%= link_to('HOME', '/')  %></li>
            <% if !current_user.present? %>
              <li class="font_Playfair"><%= link_to('SIGN UP', new_user_registration_path)  %> </li>
              <li class="font_Playfair"><%= link_to('SIGN IN', new_user_session_path)  %> </li>
            <% else %>
              <li class="font_Playfair"><%= link_to('SIGN OUT', destroy_user_session_path, :method => :delete) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
  